drop database generationg1;

create database generationg1 character set 'utf8' collate 'utf8_spanish_ci';

use generationg1;

CREATE TABLE registros(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    codigo_registro varchar(50) NOT NULL,
    rut varchar(50) NOT NULL
);

CREATE TABLE cursos(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre varchar(30) NOT NULL,
    descripcion varchar(100)
);

CREATE TABLE direcciones(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre varchar(30) NOT NULL,
    numero int not null,
    region_id int,
    ciudad_id int,
    pais_id int
);

CREATE TABLE alumnos(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre varchar(50) NOT NULL,
    apellido varchar(50) NOT NULL,
    edad int,
    curso_id int,
    direccion_id int,
    registro_id int
);

-- FOREING KEY
ALTER TABLE alumnos
ADD CONSTRAINT FK_direccion_id -- asignar nombre a la relacion
FOREIGN KEY (direccion_id) REFERENCES direcciones(id),
ADD CONSTRAINT FK_curso_id -- asignar nombre a la relacion
FOREIGN KEY (curso_id) REFERENCES cursos(id),
ADD CONSTRAINT FK_registro_id -- asignar nombre a la relacion
FOREIGN KEY (registro_id) REFERENCES registros(id)
;


CREATE TABLE regiones(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre varchar(50) NOT NULL,
    numero_romano varchar(50) NOT NULL
    );

CREATE TABLE paises(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre varchar(100) not null
);

CREATE TABLE ciudades(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
   	nombre varchar(50) not null
);

-- FOREING KEY
ALTER TABLE direcciones
ADD CONSTRAINT FK_regiones_id -- asignar nombre a la relacion
FOREIGN KEY (region_id) REFERENCES regiones(id),
ADD CONSTRAINT FK_paises_id -- asignar nombre a la relacion
FOREIGN KEY (pais_id) REFERENCES paises(id),
ADD CONSTRAINT FK_ciudades_id -- asignar nombre a la relacion
FOREIGN KEY (ciudad_id) REFERENCES ciudades(id)
;

INSERT INTO regiones (nombre, numero_romano) VALUES
('ARICA Y PARINACOTA','XV'),
('TARAPACA','I'),
('ANTOFAGASTA','II'),
('ATACAMA ','III'),
('COQUIMBO ','IV'),
('VALPARAISO ','V'),
('DEL LIBERTADOR GRAL. BERNARDO OHIGGINS ','VI'),
('DEL MAULE','VII'),
('DEL BIOBIO ','VIII'),
('DE LA ARAUCANIA','IX'),
('DE LOS RIOS','XIV'),
('DE LOS LAGOS','X'),
('AISEN DEL GRAL. CARLOS IBANEZ DEL CAMPO ','XI'),
('MAGALLANES Y DE LA ANTARTICA CHILENA','XII'),
('METROPOLITANA DE SANTIAGO','RM');

INSERT INTO paises (nombre) VALUES 
('chile'),
('argentina'),
('bolivia'),
('peru'),
('colombia'),
('brasil'),
('venezuela'),
('ecuador'),
('guyana'),
('paraguay'),
('uruguay'),
('suriname'),
('trinidad y tobago');

insert into ciudades (nombre) values
('Puente Alto'),
('Maipú'),
('Santiago'),
('La Florida'),
('Antofagasta'),
('Viña del Mar'),
('San Bernardo'),
('Valparaíso'),
('Las Condes'),
('Temuco'),
('Peñalolén'),
('Rancagua'),
('Arica'),
('Concepción'),
('Quilicura'),
('Ñuñoa'),
('Talca'),
('Pudahuel'),
('Coquimbo'),
('La Serena'),
('Iquique'),
('La Pintana'),
('Puerto Montt'),
('Chillán'),
('El Bosque'),
('Calama'),
('Recoleta'),
('Copiapó'),
('Valdivia'),
('Quilpué'),
('Talcahuano'),
('Osorno'),
('Renca'),
('Los Ángeles'),
('Providencia'),
('Estación Central'),
('Cerro Navia'),
('San Pedro de la Paz'),
('Conchalí'),
('Curicó'),
('Villa Alemana'),
('Punta Arenas'),
('La Granja'),
('Macul'),
('Coronel'),
('Quinta Normal'),
('San Miguel'),
('Alto Hospicio'),
('Lo Barnechea'),
('Pedro Aguirre Cerda'),
('Independencia'),
('Lo Espejo'),
('Huechuraba'),
('Lo Prado'),
('San Joaquín'),
('La Reina'),
('Hualpén'),
('La Cisterna'),
('Colina'),
('San Antonio'),
('Chiguayante'),
('Vitacura'),
('Peñaflor'),
('San Ramón'),
('Cerrillos'),
('Ovalle'),
('Linares'),
('Quillota'),
('Melipilla'),
('Buin'),
('San Felipe'),
('Los Andes'),
('San Fernando'),
('Talagante'),
('Cauquenes'),
('Coyhaique'),
('Machalí'),
('Angol'),
('La Calera'),
('Penco'),
('Vallenar'),
('Lota'),
('Tomé'),
('Alerce'),
('Padre Las Casas'),
('Concón'),
('Placilla de Peñuelas'),
('Limache'),
('Rengo'),
('Lampa'),
('Molina'),
('Constitución'),
('Castro'),
('San Carlos'),
('Villarrica'),
('Paine'),
('Parral'),
('Maule'),
('Curanilahue'),
('El Monte'),
('San Javier'),
('Graneros'),
('Ancud'),
('Chillán Viejo'),
('La Unión'),
('Quintero'),
('Puerto Varas'),
('Victoria'),
('Tocopilla'),
('Lautaro'),
('Mulchén'),
('Labranza'),
('Nacimiento'),
('Santa Cruz'),
('Lebu'),
('San Vicente de Tagua Tagua'),
('Cartagena'),
('Illapel'),
('San Clemente'),
('Hualqui'),
('La Cruz'),
('Cañete'),
('La Ligua'),
('Puerto Natales'),
('Nueva Imperial'),
('Curacaví'),
('Casablanca'),
('Llaillay'),
('Arauco'),
('Quellón'),
('Pucón'),
('Puerto Aysén'),
('lampa'),
('Río Bueno'),
('Chimbarongo'),
('Lampa'),
('Pitrufquén'),
('Collipulli'),
('Laja'),
('Calbuco'),
('Vicuña'),
('Caldera'),
('Loncoche'),
('Los Álamos'),
('Cabrero'),
('El Quisco'),
('Traiguén'),
('Isla de Maipo'),
('Los Vilos'),
('Salamanca'),
('Llanquihue'),
('Frutillar'),
('Mejillones'),
('Pichilemu'),
('Mostazal'),
('Curacautín'),
('Purranque'),
('Olmué'),
('Pudahuel'),
('Isla de maipo'),
('Carahue'),
('Paillaco'),
('Panguipulli'),
('Chañaral'),
('Bulnes'),
('Chicureo'),
('Taltal'),
('Cabildo'),
('Yungay'),
('Requínoa'),
('Coelemu'),
('San Esteban'),
('Quillón'),
('Andacollo'),
('Tierra Amarilla'),
('El Melón'),
('Mariquina'),
('Yumbel'),
('Los Lagos'),
('Calle Larga'),
('Santa Juana'),
('Teno'),
('Quirihue'),
('Hijuelas'),
('Pozo Almonte'),
('Coihueco'),
('Algarrobo'),
('Lo Miranda'),
('Nogales'),
('Pirque'),
('Nancagua'),
('Gorbea'),
('Peumo'),
('Lanco'),
('Las Ventanas'),
('Villa Alegre'),
('Rinconada'),
('Santa Bárbara'),
('Los Muermos'),
('Calera de Tango'),
('Tucapel'),
('Catemu'),
('Las Cabras'),
('Colina'),
('Santa María'),
('Purén'),
('Doñihue'),
('Fresia'),
('Diego de Almagro'),
('Quinta de Tilcoco'),
('Cunco'),
('Isla de Pascua'),
('Dalcahue'),
('Longaví'),
('Futrono'),
('Huasco'),
('Maule'),
('Buin'),
('Mostazal'),
('El Tabo'),
('Río Negro'),
('Colbún'),
('Putaendo'),
('Codegua'),
('Monte Águila'),
('Monte Patria'),
('Renaico'),
('Romeral'),
('Vilcún'),
('San José de Maipo'),
('Monte Patria'),
('Santo Domingo'),
('Chépica'),
('Hospital'),
('Diego de Almagro'),
('Porvenir'),
('Combarbalá'),
('Hualañé'),
('Punitaqui'),
('Cajón'),
('Chonchi'),
('Pichidegua'),
('Coquimbo'),
('Tiltil'),
('Rauco'),
('Retiro'),
('El Tabo'),
('Coltauco'),
('Freire'),
('Olivar'),
('San Pedro de Atacama'),
('Melipilla'),
('Peralillo'),
('Puchuncaví'),
('Arauco'),
('Chile Chico'),
('Cochrane'),
('Cabo de Hornos'),
('Putre'),
('Chaitén');

/*
-- INSERTAR DATOS
insert into cursos(nombre, descripcion)  VALUES 
('Alfa','aplicados'), 
('Beta','inteligentes'),
('Gamma','Astutos');
​
insert into registros(codigo_registro, rut) VALUES
('ZP34534', '123456'),
('ZP34534', '1234456'),
('ZP34534', '1234456');
​
insert into direcciones(nombre, numero, ciudad) VALUES
('Vicuna Mackena', '234', 'Santiago'),
('Llico', '17', 'San Joaquin'),
('Colombia', '432', 'La Florida');
​
insert into alumnos(nombre, apellido, edad, curso_id, direccion_id, registro_id) VALUES
('Esteban', 'Castaneda', '27', '1', '2', '3'),
('Leonardo', 'Utreras', '25', '1', '1', '2'),
('Mati', 'Rebolledo', '28', '2', '3', '1');
*/